### ISSUE TITLE
Create absolute transformer

### ISSUE THREAD

**Issue by GoodGuyGoose** [integreat-io/integreat-transformers#81]
Create a transformer which will turn a number into the absolute value of itself.  This could be done as an independent transformer or an operator of `math`.

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implement the absolute value operation in the math transformer. This includes adding a new case in the switch statement for the 'abs' operator, and implementing the corresponding function.

You can review changes in this commit: https://github.com/lattaai13/integreat-io-integreat-transformers-81/commit/d7f22932de8cb28563a85f00da77d9fd25548fed.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
